import{a as w,S as b,i as h}from"./assets/vendor-tnUJPedx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();const P="11539560-6ff438bd7cc613d70e4d35abc",S="https://pixabay.com/api/";let u=1,g="";async function m(e){const t={key:P,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:u,per_page:40},n=`${S}?${new URLSearchParams(t)}`;try{return(await w.get(n)).data}catch(i){throw console.error("Error fetching data from Pixabay API:",i),i}}function v(){u=1}function q(){u+=1}function E(e){g=e}function M(){return g}let c;function $(){c=new b(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom",overlayOpacity:1,showCounter:!1})}function B(e){const t=document.querySelector("#gallery"),n=e.map(I).join("");t.insertAdjacentHTML("beforeend",n),c?c.refresh():$()}function I({largeImageURL:e,webformatURL:t,tags:n,likes:i,views:r,comments:o,downloads:s}){return`  
    <a href="${e}" class="gallery-item">  
      <img src="${t}" alt="${n}" />  
      <div class="image-info">  
        <p><strong>Likes</strong> ${i}</p>  
        <p><strong>Views</strong> ${r}</p>  
        <p><strong>Comments</strong> ${o}</p>  
        <p><strong>Downloads</strong> ${s}</p>  
      </div>  
    </a>`}const a={form:document.querySelector("#search-form"),input:document.querySelector("#search-input"),loader:document.querySelector("#loader"),gallery:document.querySelector("#gallery"),loadMoreButton:document.querySelector(".load-more-button")};a.form.addEventListener("submit",O);a.loadMoreButton.addEventListener("click",x);async function O(e){e.preventDefault();const t=a.input.value.trim();if(!t){l("Please enter a search term!"),f();return}v(),E(t),f(),p();try{const n=await m(t);y(n)}catch{l("Something went wrong! Please try again later.")}finally{L()}a.input.value=""}async function x(){const e=M();q(),p();try{const t=await m(e);y(t)}catch{l("Something went wrong! Please try again later.")}finally{L()}}function y(e){const{hits:t,totalHits:n}=e;if(t.length===0){d("Sorry, there are no images matching your search query. Please try again!"),a.loadMoreButton.classList.add("hidden");return}B(t),a.loadMoreButton.classList.remove("hidden"),(t.length<40||n<=a.gallery.children.length)&&(a.loadMoreButton.classList.add("hidden"),d("We're sorry, but you've reached the end of search results.")),R()}function p(){a.loader.classList.remove("hidden")}function L(){a.loader.classList.add("hidden")}function l(e){h.error({title:"Error",message:e,position:"topRight",timeout:2e3})}function d(e){h.info({title:"",message:e,position:"topRight",timeout:3e3})}function f(){a.gallery.innerHTML=""}function R(){const{height:e}=a.gallery.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
