import{a as m,S as h,i as f}from"./assets/vendor-tnUJPedx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=i(r);fetch(r.href,o)}})();const p="11539560-6ff438bd7cc613d70e4d35abc",g="https://pixabay.com/api/";function y(e){const t={key:p,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0},i=`${g}?${new URLSearchParams(t)}`;return m.get(i).then(n=>n.data.hits).catch(n=>{throw console.error("Error fetching data from Pixabay API:",n),n})}let c;function L(){c=new h(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom",overlayOpacity:1,showCounter:!1})}function b(e){const t=document.querySelector("#gallery");t.innerHTML="";const i=e.map(S).join("");t.innerHTML=i,c?c.refresh():L()}function S({largeImageURL:e,webformatURL:t,tags:i,likes:n,views:r,comments:o,downloads:s}){return`  
    <a href="${e}" class="gallery-item">  
      <img src="${t}" alt="${i}" />  
      <div class="image-info">  
        <p><strong>Likes</strong> ${n}</p>  
        <p><strong>Views</strong> ${r}</p>  
        <p><strong>Comments</strong> ${o}</p>  
        <p><strong>Downloads</strong> ${s}</p>  
      </div>  
    </a>`}const a={form:document.querySelector("#search-form"),input:document.querySelector("#search-input"),loader:document.querySelector("#loader"),gallery:document.querySelector("#gallery")};function w(){a.loader.classList.remove("hidden")}function l(){a.loader.classList.add("hidden")}function d(e){f.error({title:"Error",message:e,position:"topRight",timeout:2e3})}function P(e){f.info({title:"",message:e,position:"topRight",timeout:3e3})}function u(){a.gallery.innerHTML=""}function v(e){e.preventDefault();const t=a.input.value.trim();if(!t){d("Please enter a search term!"),u();return}u(),q(t),a.input.value=""}function q(e){w(),y(e).then(t=>{l(),$(t)}).catch(t=>{l(),d("Something went wrong! Please try again later."),console.error("Error fetching images:",t)})}function $(e){e.length===0?P("Sorry, there are no images matching your search query. Please try again!"):b(e)}a.form.addEventListener("submit",v);
//# sourceMappingURL=index.js.map
